<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Voyage extends \App\Entity\Voyage implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'DateDepart' => [parent::class, 'DateDepart', null],
        "\0".parent::class."\0".'DateRetour' => [parent::class, 'DateRetour', null],
        "\0".parent::class."\0".'Description' => [parent::class, 'Description', null],
        "\0".parent::class."\0".'NomVoyage' => [parent::class, 'NomVoyage', null],
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null],
        "\0".parent::class."\0".'destination' => [parent::class, 'destination', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'DateDepart' => [parent::class, 'DateDepart', null],
        'DateRetour' => [parent::class, 'DateRetour', null],
        'Description' => [parent::class, 'Description', null],
        'NomVoyage' => [parent::class, 'NomVoyage', null],
        'categorie' => [parent::class, 'categorie', null],
        'destination' => [parent::class, 'destination', null],
        'id' => [parent::class, 'id', null],
        'prix' => [parent::class, 'prix', null],
        'reservations' => [parent::class, 'reservations', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
