<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '91c5d3041fd37b5f0afa51b154683bf1',
  'DATABASE_URL' => 'mysql://ArtVoyage:ArtVoyage@127.0.0.1:3306/ArtVoyage?serverVersion=8.2.0&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'smtp://arthur.zulpukharov.simplon@gmail.com:lysa%20zqbh%20bulp%20zgyj@smtp.gmail.com:587',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
);
