<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYS2qMxU\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYS2qMxU/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerYS2qMxU.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerYS2qMxU\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerYS2qMxU\App_KernelProdContainer([
    'container.build_hash' => 'YS2qMxU',
    'container.build_id' => '9950af49',
    'container.build_time' => 1715691478,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYS2qMxU');
