<?php

namespace ContainerYS2qMxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CsyhYv6Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.CsyhYv6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CsyhYv6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'statut' => ['privates', '.errored..service_locator.CsyhYv6.App\\Entity\\Statut', NULL, 'Cannot autowire service ".service_locator.CsyhYv6": it needs an instance of "App\\Entity\\Statut" but this type has been excluded in "config/services.yaml".'],
        ], [
            'statut' => 'App\\Entity\\Statut',
        ]);
    }
}
