<?php

namespace ContainerYS2qMxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatut2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.Li8_sjr.App\Entity\Statut' shared service.
     *
     * @return \App\Entity\Statut
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Li8_sjr": it needs an instance of "App\\Entity\\Statut" but this type has been excluded in "config/services.yaml".');
    }
}
