<?php

namespace ContainerYS2qMxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatutControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\StatutController' shared autowired service.
     *
     * @return \App\Controller\StatutController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\StatutController'] = $instance = new \App\Controller\StatutController();

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\StatutController', $container));

        return $instance;
    }
}
