<?php

namespace ContainerYS2qMxU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatutTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\StatutType' shared autowired service.
     *
     * @return \App\Form\StatutType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\StatutType'] = new \App\Form\StatutType();
    }
}
